config/routes.rb
Rails.application.routes.draw do
  

  root "pictures#index"
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation {email.downcase!}
  has_secure_password
  validates :password, length: { minimum: 6 }

  mount_uploader :image, ImageUploader
  
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required

    private

    def login_required
    redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite_pictures = current_user.favorite_pictures
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  def index
    @pictures = Picture.all.where.not(image: nil)
    @user = current_user
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    @user = current_user
    respond_to do |format|
      if @picture.save
        # UserMailer.user_mail(@user,@picture).deliver
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
  end

  private
  
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to pictures_path(@user.id)
      else
          render :new
      end
  end

  def show
      @user = User.find(params[:id])
      @pictures = Picture.where(user_id: current_user.id).where.not(image: nil)
      
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    respond_to do |format|
      
        if @user.update(user_params)
          
          format.html { redirect_to user_url(@user), notice: "Picture was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity, notice: "Failed."}
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :image, :image_cache, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
      current_user.present?
  end
end

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<% # if @favorite_pictures.present? %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Image</th>
        <th>Content</th>
        
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @favorite_pictures.each do |picture| %>
        <tr>
          <td><%= picture.title %></td>
          <td><%= image_tag picture.image.url, size: "200x100" %></td>
          <td><%= picture.content %></td>
          <td><%= link_to 'Show', picture %></td>
          <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
          <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% # end %>

<br>

<%= link_to '画像一覧', pictures_path %>
<%= link_to 'New Picture', new_picture_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramCloneExam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <%= link_to t('.Profile'), user_path(current_user.id)%>
    <%= link_to t('.Logout'), session_path(current_user.id), method: :delete%>
    <% else %>
    <%= link_to t('.Signin'), new_user_path %>
    <%= link_to t('.Login'), new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @picture.title %></p>
  <p>本文:<%= @picture.content %></p>
  <%= form.submit  "投稿する" %>

  <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th><%= t('.User') %></th>
      <th><%= t('.Title') %></th>
      <th><%= t('.Image') %></th>
      <th><%= t('.Content') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.user.name %>さん</td>
        <td><%= picture.title %></td>
        <td><%= image_tag picture.image.url, size: "200x100" %></td>
        <td><%= picture.content %></td>
        <td><%= link_to t('.Show'), picture %></td>
        <% if picture.user == @user %>
        <td><%= link_to t('.Edit'), edit_picture_path(picture) %></td>
        <td><%= link_to t('.Destroy'), picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.New Picture'), new_picture_path %>

app/views/pictures/new.html.erb
<h1><%= t('.New Picture') %></h1>

<%= render 'form', picture: @picture %>

<%= link_to t('.Back'), pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/edit.html.erb
<h1>編集画面</h1>

<%= form_with(model:@user,local:true, url: user_path) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %>
<br>
<%= f.label :email %><br>
<%= f.email_field :email %>
<br>
<%= f.label :password %><br>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %>

<br>
<%= f.label :image %>
<%= image_tag(@user.image.url) if @user.image && @user.image.url %>
<%= f.file_field :image %>
<%= f.hidden_field :image_cache %>


<br>
<br>
<%= f.submit "編集する" %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with(model:@user,local:true) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Create my account" %>

<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %>のページ</h2>
<h2>メールアドレス：<%= @user.email %></h2>

<p><%= image_tag @user.image.url, size: "600x300" if @user.image.present? %></p>
<h4><%= link_to 'プロフィールを編集する', edit_user_path %></h4>
<br>
<br>
<br>
<h3>自分の投稿</h3>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= image_tag picture.image.url, size: "200x100" %></td>
        <td><%= picture.content %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '画像一覧', pictures_path %>
<br>
<%= link_to 'お気に入り一覧', favorites_path %>
<br>
<%= link_to '新しく投稿する', new_picture_path %>